version: '2'
services:
#    elasticsearch:
#       image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
#       container_name: elasticsearch
#       network_mode: "host"
#       ports:
#         - "9200:9200"
#       environment:
#         ES_JAVA_OPTS: "-Xmx512m -Xms512m"
#    logstash:
#       image: docker.elastic.co/logstash/logstash:6.4.0
#       network_mode: "host"
#       container_name: logstash
#       volumes:
#         - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#       depends_on:
#         - elasticsearch
#       environment:
#         ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#    kibana:
#        image: docker.elastic.co/kibana/kibana-oss:6.4.0
#        network_mode: "host"
#        volumes:
#          - ./kibana/kibana.yml/:/usr/share/kibana/config/kibana.yml
#        ports:
#          - "5601:5601"
#        depends_on:
#          - elasticsearch
#        environment:
#          ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"




